= Type et classe
== Type
* Un _type_ est un modèle abstrait réunissant à un haut degré les traits essentiels de tous les êtres ou de tous les objets de même nature
* En informatique, un _type (de donnée)_ spécifie:
** l'ensemble des valeurs possibles pour cette donnée (définition en _extension_),
** l'ensemble des opérations applicables à cette donnée (définition en _intention_).
* Un type spécifie l'_interface_ par laquelle une donnée peut être manipulée

== Exemple : un type Déplaçable

[plantuml,deplacable,png]
....
interface Déplaçable {
    +translate(dx: réel, dy: réel)
}
....

== Exemple : les classes `Cercle2D` et `Point2D`

.Diagramme de classes UML
[plantuml,classe_point_cercle,png]
....
class Point2D {
    - x : réel
    - y : réel
    +translate(dx: réel, dy: réel)
}

class Cercle2D {
    - rayon : réel
    +translate(dx: réel, dy: réel)
}

Cercle2D *-- Point2D
....

* Un rectangle représente une classe
** 1er pavé: nom de la classe
** 2ième pavé: attributs
** 3ième pavé: signature des méthodes
* en général, les attributs sont privés et les méthodes publiques

== Application : modélisation d'un robot
On veut modéliser des robots se déplaçant sur un terrain.
Ce terrain est découpé en cases carrées repérées par deux coordonnées.
Chaque case peut être vide ou contenir un mur ou un robot.
Les robots sont très rudimentaires et ne disposent que d'une boussole.
Ils ne connaissent donc que leur orientation (Nord, Est, Sud, Ouest).
Un robot doit pouvoir avancer d'une case et tourner d'un quart de tour à droite.
Un robot ne peut se déplacer d'une case à une autre que si la case de destination est vide.

. Représenter en UML la classe `Robot`
. Faire de même avec la classe `Terrain`
. Représenter sur un diagramme de séquence les échanges de messages pour le déplacement d'un robot

On suppose maintenant qu'un robot peut en détecter un autre qui passe devant lui.
Par exemple, quand un robot se déplace, il peut passer dans le champ de vision d'un autre.
Ce dernier devra alors être averti.

. Modifier le diagramme précédent pour y intégrer la détection des déplacements

ifndef::masterdoc[]
== Diagramme de classe

[plantuml,robot_class,png]
....
class Robot {
  - terrain : Terrain
  - orientation : Direction
  + Robot(terrain : Terrain, depart : Position, orientation : Direction)
  + getOrientation() : Direction
  + avance()
  + tourneADroite()
}
class Terrain {
  - cases : Case[*]
  + Terrain(tailleX, tailleY, murs : Position[*])
  + ajouterRobot(robot : Robot, origine : Position)
  + avancerRobot(robot : Robot)
}
Robot "*" -> Terrain : évolue sur >
....

== Déplacer un robot

[plantuml,robot_seq1,png]
....
actor Application

Application -> r2d2: avance()
activate r2d2

r2d2 -> tatooine: avancerRobot(r2d2)
activate tatooine
tatooine -> r2d2 : getOrientation()
tatooine --> r2d2 : Ok
deactivate tatooine

r2d2 --> Application : Ok
deactivate r2d2
....
endif::masterdoc[]
