= A Course Template using AsciiDoctor
Stéphane Lopes <stephane.lopes@uvsq.fr>

This project is a template for computer science course materials.
The template uses https://asciidoctor.org/[Asciidoctor] source files to generate various documents (https://revealjs.com/#/[Reveal.js] slides, HTML "book").

== Structure of the project
The main file of the project is link:index.adoc[index.adoc].
It includes the chapters of the course which are in their own directory.
Images are in the `figs` directory in each chapter.
Source code examples are put in the `examples` directory.
An option for code examples is to use https://github.com/ingydotnet/git-subrepo[git-subrepo] to integrate examples from another git repository.

Metadata about the course (author and version) are in the file link:meta.adoc[meta.adoc]
Configuration parameters specific to book output are in link:index.adoc[index.adoc].
Parameters common to book and slide output are in link:attributes.adoc[attributes.adoc].

== Project building
Building the project requires a https://www.ruby-lang.org/[Ruby] environment.
More precisely,
* https://rubygems.org/[Ruby packages] (gems) are managed with https://bundler.io/[bundler],
* building the project required https://ruby.github.io/rake/[rake], and
* http://graphviz.org/[graphviz] is used for some diagrams.

=== Tools setup (on Debian/Linux, first time only)
[source,bash,indent=0]
----
$ sudo apt-get update && sudo apt-get -y install bundler
----

=== Ruby dependencies setup (first time only)
----
$ bundle install
----

=== Course building
----
$ rake
----

== See also
* https://asciidoctor.org/[Asciidoctor]
* https://revealjs.com/#/[Reveal.js]
